### ISSUE TITLE
The online version does not work

### ISSUE THREAD

**Issue by OndrejSpanel** [n8vm/B-Spline-Curve-Editor#1]
I wanted to try some spline experiments in your editor, as it looks quite nice, but unfortunately following link in the README does not work: http://n8vm.github.io/B-Spline-Curve-Editor/

**Comment by natevm** [comment]
Ah, good catch. I changed my username to "natevm", but that seems to have broken some old github URLs. Can you try it now and see if it works for you?

**Comment by OndrejSpanel** [comment]
Works fine. Thanks a lot for the quick fix.
